"""allow not unique name

Revision ID: 330a754df44c
Revises: 700bda68d5c4
Create Date: 2023-09-24 21:22:48.132631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330a754df44c'
down_revision: Union[str, None] = '700bda68d5c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Devices_name_key', 'Devices', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Devices_name_key', 'Devices', ['name'])
    # ### end Alembic commands ###
