"""Create_DB_models

Revision ID: 7428eb5a2f13
Revises: 
Create Date: 2023-09-22 15:22:47.448378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7428eb5a2f13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Devices',
    sa.Column('bid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('max_height', sa.Float(), nullable=False),
    sa.Column('last_emptied', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('bid'),
    sa.UniqueConstraint('identifier'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Tags',
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('DataPoints',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('gas', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('humidity_inside', sa.Float(), nullable=False),
    sa.Column('humidity_outside', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bid'], ['Devices.bid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bid', 'timestamp')
    )
    op.create_table('DevicesTags',
    sa.Column('bid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['bid'], ['Devices.bid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['name'], ['Tags.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bid', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DevicesTags')
    op.drop_table('DataPoints')
    op.drop_table('Tags')
    op.drop_table('Devices')
    # ### end Alembic commands ###
