"""Added a new temperature column

Revision ID: e102fe16b464
Revises: 330a754df44c
Create Date: 2023-09-29 15:07:14.989562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e102fe16b464'
down_revision: Union[str, None] = '330a754df44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DataPoints', sa.Column('temperature', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DataPoints', 'temperature')
    # ### end Alembic commands ###
